### ISSUE TITLE
KeyError:1 during Classification

### ISSUE THREAD

**Issue by Hannes-Ole** [HAFL-WWI/TBk#34]
Running identical configurations on different systems (same data and settings, different computers, QGIS installations and Setup):
1. QGIS 3.34.4, execution via script (in pyCharm, M05407)
2. QGIS 3.34.0, execution via QGIS plugin (hara04)

The second variant fails with the following feedback:

> Loading resulting layers
> Algorithm 'Generate BK' finished
> QGIS version: 3.34.0-Prizren
> QGIS code revision: ffbdd67881
> Qt version: 5.15.3
> Python version: 3.9.5
> GDAL version: 3.8.0
> GEOS version: 3.12.1-CAPI-1.18.1
> PROJ version: Rel. 9.3.0, September 1st, 2023
> PDAL version: 2.6.0 (git-version: e4d82c)
> Algorithm started at: 2024-04-25T06:25:54

![grafik](https://github.com/HAFL-WWI/TBk/assets/72789281/ebf0242a-28c0-496b-9b71-bcfafe315cd6)

> Traceback (most recent call last):
> File "D:\Users/hbh1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\tbk_qgis\tbk\bk_core\tbk_qgis_algorithm.py", line 518, in processAlgorithm
> run_stand_classification(working_root, tmp_output_folder,
> File "D:\Users/hbh1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\tbk_qgis\tbk\bk_core\tbk_create_stands.py", line 217, in run_stand_classification
> CH.add_vhm_stats(outputVectorFilePath, inputFilePath)
> File "D:\Users/hbh1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\tbk_qgis\tbk\bk_core\Classification.py", line 163, in add_vhm_stats
> if stats[fid].get('max') is not None and stats[fid].get('max') != NULL:
> KeyError: 1
> 
> Execution failed after 8219.83 seconds (2 hours 16 minutes 60 seconds)

`KeyError: 1` indicating, that he doesn't find fid 1? Checking the generated output bk_process\stand_boundaries.gpkg however shows fids 1 and ID 1 being present. Need to reproduce in a debug environment to see what's going on.

![grafik](https://github.com/HAFL-WWI/TBk/assets/72789281/d9594e5f-9e02-4a75-b091-6e7b3ca2255f)
![grafik](https://github.com/HAFL-WWI/TBk/assets/72789281/e712fc68-fdf0-4984-9eea-dbeff9eac686)

It happens after classification, when adding attributes to the first gpkg.

> --- 13.16 minutes, classification finished ---
> File P:\HAFL\7 WWI\74a FF WG\742a Aktuell\L.012359-52-WFOM_TBk_II\06_TBk_Fribourg\Daten\tbk_2019\20240425-0625\bk_process\classified_raw.tif saved
> File P:\HAFL\7 WWI\74a FF WG\742a Aktuell\L.012359-52-WFOM_TBk_II\06_TBk_Fribourg\Daten\tbk_2019\20240425-0625\bk_process\hmax.tif saved
> File P:\HAFL\7 WWI\74a FF WG\742a Aktuell\L.012359-52-WFOM_TBk_II\06_TBk_Fribourg\Daten\tbk_2019\20240425-0625\bk_process\hdom.tif saved
> File P:\HAFL\7 WWI\74a FF WG\742a Aktuell\L.012359-52-WFOM_TBk_II\06_TBk_Fribourg\Daten\tbk_2019\20240425-0625\bk_process\classified_smooth_1.tif saved
> File P:\HAFL\7 WWI\74a FF WG\742a Aktuell\L.012359-52-WFOM_TBk_II\06_TBk_Fribourg\Daten\tbk_2019\20240425-0625\bk_process\classified_smooth_2.tif saved
> --- 14.58 minutes, raster smoothed and saved  ---
> File P:\HAFL\7 WWI\74a FF WG\742a Aktuell\L.012359-52-WFOM_TBk_II\06_TBk_Fribourg\Daten\tbk_2019\20240425-0625\bk_process\stand_boundaries.gpkg saved
> --- 56.66 minutes, vector file saved ---
> --- 136.9 minutes, stand attributes added ---
> stats input file path P:/HAFL/7 WWI/74a FF WG/742a Aktuell/L.012359-52-WFOM_TBk_II/06_TBk_Fribourg/Daten/tbk_2019/VHM_10m.tif

**Comment by Hannes-Ole** [comment]
Has was likely fixed in the general overhaul and refactoring.
