### ISSUE TITLE
QGIS processing Log output not reliable

### ISSUE THREAD

**Issue by Hannes-Ole** [HAFL-WWI/TBk#6]
Our processing output doesn’t show up reliably.
QGIS log output gets written only once (and subsequent runs have nearly no output in the processing console except for errors).

The issue can be reproduced as follows:
1. Run “Generate BK” algorithm.
2. The Log Output shows up correctly.
3. Close Algorithm window after execution (“finished”)
4. Open Algorithm “Generate BK” again and run with same configuration: The Log output doesn’t show up, only errors print in the Processing Log.

EXPECTED OUTPUT (works on first run)
![grafik](https://github.com/HAFL-WWI/TBk/assets/72789281/b4272086-5f33-4458-a494-11191f496eeb)

OUTPUT MISSING (after closing/opening window and running again):
![grafik](https://github.com/HAFL-WWI/TBk/assets/72789281/8440cede-6970-483c-89c3-374af09249b9)

The Python console is showing this (when this occurs):

> --- Logging error ---
> Traceback (most recent call last):
>   File "C:\OSGeo4W\apps\Python39\lib\logging\__init__.py", line 1086, in emit
>     stream.write(msg + self.terminator)
> AttributeError: 'NoneType' object has no attribute 'write'
> Call stack:
>   File "C:\Users/hbh1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\tbk_qgis\tbk\bk_core\tbk_qgis_algorithm.py", line 350, in processAlgorithm
>     rootLogger.info('Run TBk')
> Message: 'Run TBk'
> Arguments: ()
> --- Logging error ---
> Traceback (most recent call last):
>   File "C:\OSGeo4W\apps\Python39\lib\logging\__init__.py", line 1086, in emit
>     stream.write(msg + self.terminator)
> AttributeError: 'NoneType' object has no attribute 'write'
> Call stack:
>   File "C:\Users/hbh1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\tbk_qgis\tbk\bk_core\tbk_qgis_algorithm.py", line 366, in processAlgorithm
>     rootLogger.info('Stand delineation')
> Message: 'Stand delineation'
> Arguments: ()
> --------------------------------------------

![grafik](https://github.com/HAFL-WWI/TBk/assets/72789281/7fb26dda-770e-458b-87f5-9ab3eca3bfd3)

**Comment by davidcout2** [comment]
> This is a problem with BKAG, too. And I just realized you can't delete it's output .log file while QGIS is still opened. This might be a lead; maybe the whole thing (and the non-deleted temp files, see [#27](https://github.com/HAFL-WWI/TBk/issues/27) ) is an issue of file contexts not being used (at all/properly).

I was in contact with Denis, and they suggested using feedback.textLog() or feedback.htmlLog(). The following code allows me to write the feedback to a file and delete it while QGIS is still open:
```python
with open(logfile_tmp_path, "w") as f:
            f.write(feedback.textLog())
```

For the other bugs, I would suggest configuring logging globally (rather than in each algorithm/tool), or setting it up in a static way to ensure that handlers:

- are not added multiple times to the logging
- are not removed when the tool/algorithm window is closed

If necessary, here is a QGIS python script I used to test, fix(not globally and not necessary nicely) and understand the problems. 

[test_logging_25_04_08.txt](https://github.com/user-attachments/files/19647438/test_logging_25_04_08.txt)
![Image](https://github.com/user-attachments/assets/4607db20-26ba-4177-9313-59c3e92d9ad9)

**Comment by Hannes-Ole** [comment]
Fixed as part of a logging overhaul in TBkProcessingAlgorithm._configure_logging (commit 0eee079, dev/modularized).

Root cause of the AttributeError: 'NoneType' object has no attribute 'write' / missing output on reruns: the root logger's handlers were bound once and then silently reused (or left pointing at a dead stream/old file) across separate algorithm runs within the same QGIS session, instead of being reconfigured per run.

Fix:
- A console handler that re-resolves sys.stderr on every emit() instead of binding it once at construction, so it recovers once QGIS's Python Console panel provides a real stream (_TBkDynamicConsoleHandler).
- File/console handlers are now explicitly torn down (removeHandler + close()) and recreated whenever a new run starts (i.e. a new output log path), instead of being reused indefinitely — this also fixes the duplicated log messages reported above (2024-09-03 comment).
- Nested processing.run() calls sharing one QgsProcessingContext (e.g. Generate BK Regionwise's per-region sub-calls) now stay anchored to the same log file instead of redirecting it mid-run.

Not adopted: the feedback.textLog()/htmlLog() approach suggested above — the direct handler fix keeps the standard logging module intact, which is needed since it's shared across submodules that don't have a feedback object.

One related, smaller point from the comments above: the log file handle is only released when the next run opens a new log path, not immediately when a run finishes — so it can still be locked against deletion right after a run while QGIS stays open. This is a minor separate concern from the "log output unreliable" issue title here; happy to open a small follow-up if it's still causing friction (possibly related to #27 ).

Closing this as the core reliability/duplication problem is resolved.
